# Generated by Django 2.2.6 on 2019-10-11 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataConnectorType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('schema', django_mysql.models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='DataConnector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('config', django_mysql.models.JSONField(default=dict)),
                ('data_connector_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_connectors', to='projects.DataConnectorType')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_connectors', to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_connectors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
