# Generated by Django 2.2.6 on 2019-10-11 14:49

from django.db import migrations, models
import django_mysql.models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20191011_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconnectortype',
            name='config',
            field=django_mysql.models.JSONField(default=projects.models.default),
        ),
        migrations.AlterField(
            model_name='dataconnectortype',
            name='label',
            field=models.CharField(default='Debezium', max_length=200),
        ),
    ]
