# Generated by Django 2.2.6 on 2019-10-16 17:32

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_auto_20191016_1732'),
        ('projects', '0003_auto_20191011_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataconnectortype',
            name='integration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_connector_types', to='integrations.Integration'),
        ),
        migrations.AlterField(
            model_name='dataconnector',
            name='config',
            field=django_mysql.models.JSONField(default=projects.models.default),
        ),
    ]
