version: "3.7"
services:
  app:
    build:
      context: .
    ports:
      - 8881:8000
    volumes:
      - ./:/usr/src/app/
    env_file: .env

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_DATABASE: eddy_backend
      MYSQL_USER: eddy_backend
      MYSQL_PASSWORD: mysqlpassword

  debezium-zookeeper:
    image: debezium/zookeeper:0.10

  debezium-kafka:
    image: debezium/kafka:0.10
    environment:
      - ZOOKEEPER_CONNECT=debezium-zookeeper:2181

  debezium-mysql:
    image: debezium/example-mysql:0.10

  debezium-connect:
    image: debezium/connect:0.10
    environment:
      - BOOTSTRAP_SERVERS=debezium-kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
