version: "3.7"
services:
  app:
    build:
      context: .
    ports:
      - 8881:8000
    links:
      - mysql
    volumes:
      - ./:/usr/src/app/
    env_file: .env

  redis:
    image: redis:6.2.3

  mysql:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: eddy_backend
      MYSQL_USER: eddy_backend
      MYSQL_PASSWORD: mysqlpassword
    
  zookeeper:
    image: debezium/zookeeper:1.5
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  
  kafka:
    image: debezium/kafka:1.5
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  connect:
    image: debezium/connect:1.5
    ports:
      - 8083:8083
    links:
      - kafka
      - mysql
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
volumes:
  mysql-data:

networks:
  default:
    external:
      name: eddy