version: "3.7"
services:
  app:
    build:
      context: .
    ports:
      - 8881:8000
    links:
      - postgres:postgres
      - mysql:mysql
    volumes:
      - ./:/usr/src/app/
    env_file: .env

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db_eddy_backend
      POSTGRES_USER: eddy_backend
      POSTGRES_PASSWORD: postgrespassword

  debezium-zookeeper:
    image: debezium/zookeeper:0.10
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  debezium-kafka:
    image: debezium/kafka:0.10
    ports:
      - 9092:9092
    links:
      - debezium-zookeeper:debezium-zookeeper
    environment:
      - ZOOKEEPER_CONNECT=debezium-zookeeper:2181

  debezium-connect:
    image: debezium/connect:0.10
    ports:
      - 8083:8083
    links:
      - debezium-kafka:debezium-kafka
      - debezium-mysql:debezium-mysql
    environment:
      - BOOTSTRAP_SERVERS=debezium-kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

  debezium-mysql:
    image: debezium/example-mysql:0.10
    ports:
      - 3307:3307
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - MYSQL_TCP_PORT=3307