version: "3.7"
services:
  app:
    build:
      context: .
    ports:
      - 8881:8000
    links:
      - mysql
    env_file: .env

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: db_eddy_backend
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
