# Generated by Django 2.2.5 on 2019-09-24 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebeziumConnectorConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_class', models.CharField(default='io.debezium.connector.mysql.MySqlConnector', max_length=200)),
                ('tasks_max', models.IntegerField(default=1)),
                ('database_hostname', models.CharField(default='mysql', max_length=200)),
                ('database_port', models.IntegerField(default=3306)),
                ('database_user', models.CharField(default='root', max_length=200)),
                ('database_password', models.CharField(default='debezium', max_length=200)),
                ('database_server_id', models.IntegerField(default='184054')),
                ('database_server_name', models.CharField(default='mysql1', max_length=200)),
                ('database_whitelist', models.CharField(default='inventory', max_length=200)),
                ('database_history_kafka_bootstrap_servers', models.CharField(default='kafka:9092', max_length=200)),
                ('database_history_kafka_topic', models.CharField(default='schema-changes.inventory', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DebeziumConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='inventory-connector', max_length=200)),
                ('config', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connector', to='debezium_connectors.DebeziumConnectorConfig')),
            ],
        ),
    ]
