# Generated by Django 2.2.5 on 2019-09-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debezium_connectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debeziumconnectorconfig',
            name='database_server_id',
            field=models.IntegerField(default='184054'),
        ),
    ]
