# Generated by Django 2.2.6 on 2019-10-16 08:34

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='config',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
