# Generated by Django 2.2.6 on 2019-10-08 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='workspaces.Workspace'),
        ),
    ]
