# Generated by Django 2.2.6 on 2019-10-08 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('integration_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='integrations.IntegrationType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='workspaces.Workspace')),
            ],
        ),
        migrations.CreateModel(
            name='DebeziumConnectorConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('connector_class', models.CharField(max_length=200)),
                ('tasks_max', models.IntegerField()),
                ('database_hostname', models.CharField(max_length=200)),
                ('database_port', models.IntegerField()),
                ('database_user', models.CharField(max_length=200)),
                ('database_password', models.CharField(max_length=200)),
                ('database_server_id', models.IntegerField()),
                ('database_server_name', models.CharField(max_length=200)),
                ('database_whitelist', models.CharField(max_length=200)),
                ('database_history_kafka_bootstrap_servers', models.CharField(max_length=200)),
                ('database_history_kafka_topic', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debezium_connector_configs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DebeziumConnector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connector', to='integrations.DebeziumConnectorConfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debezium_connectors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
