# Generated by Django 2.2.6 on 2019-10-09 14:03

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='config',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='integrationtype',
            name='config',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
