# Generated by Django 2.2.6 on 2019-10-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20191009_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debeziumconnectorconfig',
            name='user',
        ),
        migrations.DeleteModel(
            name='DebeziumConnector',
        ),
        migrations.DeleteModel(
            name='DebeziumConnectorConfig',
        ),
    ]
