# Generated by Django 2.2.6 on 2019-10-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_auto_20191013_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='supports_data_connectors',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(default='debezium', max_length=200),
        ),
        migrations.DeleteModel(
            name='IntegrationType',
        ),
    ]
