name: Continuos Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Setup Dependencies
        run: python -m pip install -r requirements.txt
      # - name: Run Tests
      #   run: python manage.py test
      - name: Build Docker image
        run: docker build . -t eddyanalytics/eddy-backend:latest
      - name: Push Docker image
        run: |
          echo '${{ secrets.CI_REGISTRY_TOKEN }}' | docker login --username eddyanalytics --password-stdin
          docker push eddyanalytics/eddy-backend:latest
      - name: Check Tag
        id: check_tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=match::true
          fi
      - name: Release Version
        if: steps.check_tag.outputs.match == 'true'
        run: |
          docker tag eddyanalytics/eddy-backend:latest eddyanalytics/eddy-backend:${GITHUB_REF##*/}
          docker push eddyanalytics/eddy-backend:${GITHUB_REF##*/}
